name: Fuse Project
on:
  release:
    types: [created]

jobs:
  fuse:
    runs-on: ubuntu-latest
    steps:
      - name: Install Lua/LuaJIT
        uses: leafo/gh-actions-lua@v10.0.0

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.3.0

      - name: Install amalg
        run: luarocks install amalg
  
      - name: Check out repository code
        uses: actions/checkout@v3
  
      - name: Show bullshit
        run: ls -la

      - name: Run amalg
        run: ~/.luarocks/bin/amalg.lua ~/src
