name: Fuse Project
on:
  release:
    types: [created]

jobs:
  fuse:
    runs-on: ubuntu-latest
    steps:
      - name: Install Lua/LuaJIT
      - uses: leafo/gh-actions-lua@v10.0.0
    
      - name: Install LuaRocks
      - uses: leafo/gh-actions-luarocks@v4.3.0
      
      - run: luarocks install amalg
      - run: amalg.lua ./src
